const types = {
  FLIP_CARD: "FLIP_CARD",
  FLIP_UNMATCHED_CARDS: "FLIP_UNMATCHED_CARDS",
  RESET_BOARD: "RESET_BOARD",
  SET_GRID_ROWS: " SET_GRID_ROWS",
  SET_GRID_COLUMNS: " SET_GRID_COLUMNS",
  SET_START_GAME: "SET_START_GAME",
};
export default types;
